### ISSUE TITLE
Handle encoding errors

### ISSUE THREAD

**Issue by gforcada** [gforcada/flake8-plone-api#2]
```
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gil/.buildout/eggs/flake8-2.4.1-py2.7.egg/flake8/reporter.py", line 74, in process_main
    self._process_main()
  File "/home/gil/.buildout/eggs/flake8-2.4.1-py2.7.egg/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/home/gil/.buildout/eggs/flake8-2.4.1-py2.7.egg/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/gil/.buildout/eggs/pep8-1.5.7-py2.7.egg/pep8.py", line 1412, in check_all
    self.check_ast()
  File "/home/gil/.buildout/eggs/pep8-1.5.7-py2.7.egg/pep8.py", line 1359, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/home/gil/.buildout/eggs/flake8_plone_api-0.4-py2.7.egg/flake8_plone_api.py", line 22, in run
    found = line.find(old_approach)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
```

**Comment by gforcada** [comment]
Largely fixed by moving to python 3 🍀
